// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using estonteco.api.DAL;

namespace estonteco.api.Migrations
{
    [DbContext(typeof(EstontecoDbContext))]
    partial class EstontecoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("estonteco.api.Model.InfoRezerwacja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("CzyZajete");

                    b.Property<bool>("CzyZarezerwowane");

                    b.Property<double>("DlugoscGeo");

                    b.Property<int>("IdParkingu");

                    b.Property<int>("Miejsce");

                    b.Property<double>("SzerokoscGeo");

                    b.HasKey("Id");

                    b.ToTable("Rezerwacje");
                });

            modelBuilder.Entity("estonteco.api.Model.Parking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nazwa");

                    b.HasKey("Id");

                    b.ToTable("Parkingi");
                });
#pragma warning restore 612, 618
        }
    }
}
